export const data = [
    {
        id: 1,
        category: "agricultural business",
        img: "/img/peter.png",
        name: "user chibuzor",
        date: "22.08.2020",
        title: "What is the best feed for broiler chickens",
        content: "How do you think I can scale my grinding business. I have machines but cant access the quantity of cassava I need to scale.",
        comments: 200,
        views: 1200,
        likes: 2300
    },
    {
        id: 2,
        category: "livestock farming",
        img: "/users/amy-burns.png",
        name: "Jamila Ahmed",
        date: "15.04.2023",
        title: "Best practices for raising dairy goats",
        content: "I'm starting a small dairy goat farm and would love to learn from experienced farmers about the best feeding, housing, and milking practices for optimal milk production and herd health.",
        comments: 85,
        views: 2750,
        likes: 325
      },
      {
        id: 3,
        category: "crop cultivation",
        img: "/users/balazs-orban.png",
        name: "Tomás Gutiérrez",
        date: "09.11.2022",
        title: "Organic pest control for tomato plants",
        content: "My tomato crop is being attacked by various pests, and I'm looking for effective organic methods to control them without using harmful chemicals. Any tried-and-true solutions from experienced organic growers?",
        comments: 112,
        views: 4620,
        likes: 780
      },
      {
        id: 5,
        category: "agricultural technology",
        img: "/users/delba-de-oliveira.png",
        name: "Emily Johnson",
        date: "03.09.2023",
        title: "Implementing precision farming techniques",
        content: "I'm interested in adopting precision farming techniques on my family's farm to improve efficiency and sustainability. Can anyone share their experiences with tools like GPS mapping, variable rate application, and yield monitoring?",
        comments: 95,
        views: 3200,
        likes: 620
      },
      {
        id: 4,
        category: "aquaculture",
        img: "/users/emil-kowalski.png",
        name: "Aarav Singh",
        date: "28.02.2024",
        title: "Optimal water quality for shrimp farming",
        content: "I recently started a shrimp farm, and I'm struggling to maintain the right water quality parameters. What are the ideal levels for pH, temperature, dissolved oxygen, and other factors for maximizing shrimp growth and survival?",
        comments: 65,
        views: 1850,
        likes: 475
      },
      {
        id: 6,
        category: "farm management",
        img: "/users/evil-rabbit.png",
        name: "Mohamed Khalid",
        date: "18.06.2023",
        title: "Efficient irrigation system for small farms",
        content: "I'm looking for cost-effective and water-efficient irrigation systems suitable for my 10-acre farm. What are the best options for drip irrigation, sprinklers, or other methods that can help me conserve water and improve crop yield?",
        comments: 72,
        views: 2400,
        likes: 380
      },
      {
        id: 7,
        category: "agricultural business",
        img: "/img/peter.png",
        name: "Sophia Lee",
        date: "11.01.2024",
        title: "Marketing strategies for local produce",
        content: "As a small-scale organic farmer, I'm struggling to find effective ways to market and sell my produce directly to consumers. Any tips or successful strategies for setting up farm stands, participating in farmers' markets, or using online platforms?",
        comments: 130,
        views: 4800,
        likes: 920
      },
      {
        id: 8,
        category: "livestock farming",
        img: "/users/guillermo-rauch.png",
        name: "Alejandro Ramírez",
        date: "27.03.2023",
        title: "Pasture management for cattle grazing",
        content: "I'm looking for advice on effective pasture management techniques to maintain healthy and productive grazing areas for my cattle herd. What are the best practices for rotational grazing, overseeding, and controlling invasive weeds?",
        comments: 90,
        views: 3100,
        likes: 520
      },
      {
        id: 9,
        category: "crop cultivation",
        img: "/users/steph-dietz.png",
        name: "Nadia Bakhti",
        date: "14.08.2023",
        title: "Companion planting for vegetable gardens",
        content: "I'm interested in implementing companion planting in my vegetable garden to improve pest control and soil health. Can anyone share their experiences with effective plant combinations and the benefits they've observed?",
        comments: 105,
        views: 3600,
        likes: 710
      }, {
        id: 10,
        category: "aquaculture",
        img: "/users/hector-simpson.png",
        name: "David Nguyen",
        date: "05.12.2023",
        title: "Sustainable fish feed alternatives",
        content: "As a fish farmer, I'm looking for sustainable and cost-effective alternatives to traditional fish feed. Has anyone had success with using insect meal, algae, or other novel ingredients in their feed formulations?",
        comments: 80,
        views: 2900,
        likes: 550
      },
      {
        id: 11,
        category: "agricultural technology",
        img: "/users/jared-palmer.png",
        name: "Anna Kowalski",
        date: "21.07.2023",
        title: "Implementing IoT in greenhouse monitoring",
        content: "I'm planning to set up a modern greenhouse and would like to incorporate IoT technologies for real-time monitoring of temperature, humidity, and other environmental conditions. What are the best IoT solutions and platforms for greenhouse automation?",
        comments: 110,
        views: 4100,
        likes: 850
      },
      {
        id: 12,
        category: "farm management",
        img: "/users/lee-robinson.png",
        name: "Fatima Bouazza",
        date: "10.04.2023",
        title: "Effective record-keeping for small farms",
        content: "As a small-scale farmer, I often struggle with keeping accurate records of my crops, livestock, expenses, and yields. Can anyone recommend user-friendly software or apps specifically designed for farm record-keeping and management?",
        comments: 75,
        views: 2800,
        likes: 420
      },
      {
        id: 13,
        category: "agricultural business",
        img: "/users/michael-novotny.png",
        name: "Michael Müller",
        date: "28.09.2023",
        title: "Agritourism opportunities for farms",
        content: "I'm considering diversifying my farm income by offering agritourism experiences like farm stays, educational tours, or on-site events. What are some successful agritourism models and marketing strategies to attract visitors?",
        comments: 120,
        views: 4500,
        likes: 880
      },
      {
        id: 14,
        category: "livestock farming",
        img: "/users/steven-tey.png",
        name: "Samantha Wilson",
        date: "16.02.2024",
        title: "Rotational grazing for sheep and goats",
        content: "I'm interested in implementing rotational grazing on my small ruminant farm to improve pasture management and animal health. Can experienced farmers share their tips and techniques for setting up effective rotational grazing systems?",
        comments: 85,
        views: 3200,
        likes: 610
      },
      {
        id: 15,
        category: "crop cultivation",
        img: "/img/peter.png",
        name: "Yusuf Akbari",
        date: "06.11.2023",
        title: "Intercropping systems for sustainable farming",
        content: "I've heard about the benefits of intercropping, where multiple crops are grown together in the same field. Can anyone share their experiences with successful intercropping systems and the advantages they've seen in terms of yield, pest control, and soil health?",
        comments: 95,
        views: 3800,
        likes: 720
      }
]

